global:
  # with this false, you cannot use item names, but you can use custom blocks
  # GLOBAL ONLY
  use-match-material: true
  chest-loot:
  -   ==: Item
      values:
        chance: .5
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_PICKAXE
        # if no amount give, defaults to 0
        damage: 1
        # if no amount given, defaults to 1
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DURABILITY: 3
  -   ==: Item
      values:
        chance: 1
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: APPLE
  -   ==: Item
      values:
        chance: 1
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: CAKE
  -   ==: Item
      values:
        chance: 1
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: EXP_BOTTLE
  sponsor-loot:

chests:
#  example:
#    # unneeded
#    inherits: exmample1
#    items: 
#    -   ==: Item
#        values:
#         # chance is not needed, without it, it defaults to 1/3.
#         # 1 is always, 0 is never
#         chance: 1
#        stack:
#          ==: org.bukkit.inventory.ItemStack
#          type: APPLE
#    -   ==: Item
#        values:
#          chance: 1
#        stack:
#          ==: org.bukkit.inventory.ItemStack
#          type: CAKE

itemsets:
# Example game
# To use one of these, when creating a game do 
# /hga add itemset <name-of-game> <name-of-itemset>  NOTE make sure there are no space in the list of itemsets
#  example:
#    # unneeded
#    inherits: exmample1
#    chest-loot: 
#    -   ==: Item
#        values:
#         # chance is not needed, without it, it defaults to 1/3.
#         # 1 is always, 0 is never
#         chance: 1
#        stack:
#          ==: org.bukkit.inventory.ItemStack
#          type: APPLE
#    sponsor-loot:
#    -   ==: Item
#        values:
#          chance: 1
#        stack:
#          ==: org.bukkit.inventory.ItemStack
#          type: CAKE

rewards:
  # Every one of the below will be given
  static:
#  -   ==: Item
#      values:
#       # chance is not needed, without it, it defaults to 1/3.
#       # 1 is always, 0 is never
#       chance: 1
#      stack:
#        ==: org.bukkit.inventory.ItemStack
#        type: APPLE
  # The max amount of items that can be given to a player randomly
  max-random: 5
  # The following will be randomly given to the player
  random:
#  -   ==: Item
#      values:
#       # chance is not needed, without it, it defaults to 1/3.
#       # 1 is always, 0 is never
#       chance: 1
#      stack:
#        ==: org.bukkit.inventory.ItemStack
#        type: APPLE

kits:
# Example
#  test:
#  -   ==: Item
#      values:
#       # chance is not needed, without it, it defaults to 1/3.
#       # 1 is always, 0 is never
#       chance: 1
#      stack:
#        ==: org.bukkit.inventory.ItemStack
#        type: APPLE