global:
  default-game: 'Test'
  
  # In minutes, the number of time to wait between update checks
  update-delay: 30
  
  # The following are default only, and will be overwritten by the setup, if applicable
  join-message: '<player> has joined the game <game>.'
  rejoin-message: '<player> has rejoined the game <game>'
  leave-message: '<player> has left the game <game>.'
  quit-message: '<player> has quit the game <game>.'
  kill-message: '<killer> killed <killed> in game <game>.'
  vote-message: '<player> is ready to play <game>. Type /hg vote when you are ready to play.'
  
  # Time, in seconds, after game starts before players can move
  default-time: 10
  
  # Number of players required to auto-start
  min-vote: 5
  
  # If players can join a game while it is running
  allow-join-during-game: false
  
  # Number of players required to start at all
  min-players: 2
  
  # If a player can rejoin a game. 
  # If false, players will lose all lives on leave. 
  # If true, lives are carried over to any rejoins
  allow-rejoin: true
  
  # If a winner gets to keep his items
  winner-keeps-items: true
  
  # number of lives a player has. 0 is unlimited
  lives: 1
  
  # whether players should clear their inventory before joining
  should-clear-inv: false
  
  # require everyone that has joined the game to start
  all-vote: false
  
  # when a player joins a game, they are auto-voted as ready. If true, all-vote is disregarded
  auto-vote: false
  
  # whether players can place blocks
  can-place-block: false
  
  # whether players can break blocks
  can-break-block: false

  # whether players can interact with blocks (Chests, Enchant tables, ect...)
  can-interact-block: false
  
  # whether players can use commands. Does not disallow HungerGames commands.
  use-command: false
  
  # whether players can teleport
  can-teleport: false
  
  # world to reload on game end if world-reload is true. NOTE: must have a "template" stored in MyHungerGames/<worldname>_template
  reload-world-name: Default_world
    
  # reload world on game end. Recommended that this be false and have setups override this
  reload-world: false
  
  # add chest and fill the first time a chest is opened
  auto-add: true
  
  # blocks players can place (NOTE: if "can-place-blocks" is false, they cannot
  # place blocks except for these blocks, and vice versa) ex: "[1]", "[1, 10, 28]"
  special-blocks-place: []
 
  # blocks players can break (NOTE: if "can-break-blocks" is false, they cannot
  # break blocks except these blocks, and vice versa) ex: "[1]", "[1, 10, 28]"
  special-blocks-break: []
 
  # blocks players can interact (NOTE: if "can-interact-blocks" is false, they cannot
  # interact with blocks except these blocks, and vice versa) ex: "[1]", "[1, 10, 28]"
  special-blocks-interact: []

  # Reset block changes after a game ends
  reset-changes: false
  
  chest-loot:
  # Example loot. Note DURABIlITY is an enchantment
  #    DIAMOND_PICKAXE:
  #        stack-size: 1
  #        chance: 0.01
  #        DURABILITY: 3
  sponsor-loot:
    
itemsets:
# Example game
# To use one of these, when creating a game do 
# /hga add itemset <name-of-game> <name-of-itemset>  NOTE make sure there are no space in the list of itemsets
#  test:
#	  chest-loot:
#	  # Example loot. Note DURABIlITY is an enchantment
#	  #    DIAMOND_PICKAXE:
#	  #        stack-size: 1
#	  #        chance: 0.01
#	  #        DURABILITY: 3
#	  sponsor-loot:
  
setups:
#  test1:
#		default-time: 5
#		min-vote: 10
#		allow-join-during-game: false
#		min-players: 2
#		allow-rejoin: false
#		winner-keeps-items: false
  